services:

  mongo-topapi-air-bnb:
    image: mongo
    container_name: mongo-topapi-air-bnb
    restart: always
    env_file:
      - ./.env.prod
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./.mongo:/data/db
    networks:
      - topapi-air-bnb

networks:
  topapi-air-bnb:
