version: '3.9'

services:

  top-api-air-bnb:
    build:
      context: .
      dockerfile: Dockerfile
    image: top-api-air-bnb:latest
    container_name: top-api-air-bnb
    restart: always
    ports:
      - 3338:3338
    env_file:
      - ./.env.prod
    networks:
      - topapi-air-bnb

networks:
  topapi-air-bnb: