services:

  top-api-air-bnb:
    build:
      context: .
      dockerfile: Dockerfile
    image: top-api-air-bnb:latest
    # image: ghcr.io/alslapp/purpleschool-api-air-bnb:main
    container_name: top-api-air-bnb
    restart: always
    env_file:
      - ./.env.prod
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - ./uploads:/opt/app/uploads/
    networks:
      - topapi-air-bnb

networks:
  topapi-air-bnb: